### ISSUE TITLE
Broken link to bot

### ISSUE THREAD

**Issue by pschfr** [peralmq/bot-wat#3]
![capture](https://cloud.githubusercontent.com/assets/490222/14716287/57984e5e-07ba-11e6-8b14-3ae6a1c07601.PNG)
When you click on the link to chat with the bot, it doesn't work? Seems like it disappeared on Facebook's end.

**Comment by Daniel15** [comment]
I noticed the same thing :( It's possible the Page is "unpublished" which means that nobody can see it apart from its creator.

**Comment by xori** [comment]
That's probably a smart thing considering `child_process.exec()`

**Comment by Daniel15** [comment]
Well, it's using something called `safe-eval` which I hope is actually safe. ¯\_(ツ)_/¯

**Comment by peralmq** [comment]
Hey, yes, sorry, I had misunderstood the Facebook Messenger bot review process. Thought that it was enough to publish the Facebook page in order to be able to receive and send messages to external people. Now the page can receive messages but those messages never make it to the server where the bot is located, and hence no response ever makes it back to you.. :(

Good news is that if you follow Facebook's guide to create a Messenger bot you can easily deploy this code and play around with it yourself. It works great to receive and send messages for the owner of the page/bot :)

I'll update you if I get the required permission from Facebook and the bot becomes publicly accessible.
